name: Dockerwin

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - winbranch

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: azdobuildagentwin
  DOCKERFILE: Dockerfile-windows

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: show env
        run: |
          echo "var is $IMAGE_NAME"
          echo "env is  $ENV:IMAGE_NAME"
          echo "env context is " ${{ env.IMAGE_NAME}}
          $VERSION="$ENV:GITHUB_RUN_ID"
          echo "version is $VERSION"
          Get-Location



      - name: Build
        run: |
          # docker build . --file Dockerfile-windows
          docker build . --file ${{ env.DOCKERFILE}} -t ${{ env.IMAGE_NAME}}
          docker image ls


      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run:  |
          $IMAGE_ID="docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME}}".ToLower()
          echo "imageid is $IMAGE_ID"
          $VERSION="$ENV:GITHUB_RUN_ID"
          echo "version is $VERSION"
          $FULLTAG="${IMAGE_ID}:${VERSION}"
          echo "fulltag is $FULLTAG"
          docker tag ${{ env.IMAGE_NAME}} $FULLTAG
          docker image ls
          docker push $FULLTAG

          
