name: Dockerwin

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: azdobuildagentwin

jobs:

  buildandpush:
    runs-on: windows-latest

    steps:
     - name: show env
       run: echo "var is $IMAGE_NAME"
       run: echo "env is  $ENV:IMAGE_NAME"
       run: type "C:\Users\runneradmin\.docker\config.json"
      
     - name: Build, Tag, Push
       uses: mattdavis0351/actions/docker-gpr@v1
       with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            image-name: $IMAGE_NAME
            dockerfile-location: Dockerfile-win